package com.kawan.lotmanchors.anchor;

import com.kawan.lotmanchors.config.AnchorConfig;
import de.jakob.lotm.entity.custom.AvatarEntity;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;

public final class UniqueAnchorManager {

    private UniqueAnchorManager() {
    }

    /**
     * Counts Error Avatars owned by the player, grouped by sequence.
     *
     * Index:
     * 0 = unused
     * 1 = Sequence 1
     * 2 = Sequence 2
     * 3 = Sequence 3
     * 4 = Sequence 4
     */
    public static int[] countErrorAvatarsBySequence(ServerPlayer player) {
        int[] counts = new int[5];

        for (ServerLevel level : player.getServer().getAllLevels()) {

            for (net.minecraft.world.entity.Entity entity : level.getAllEntities()) {

                if (!(entity instanceof AvatarEntity avatar)) {
                    continue;
                }

                if (avatar.getOriginalOwner() == null) {
                    continue;
                }

                if (!avatar.getOriginalOwner().equals(player.getUUID())) {
                    continue;
                }

                if (!"error".equalsIgnoreCase(avatar.getPathway())) {
                    continue;
                }

                int sequence = avatar.getSequence();

                if (sequence >= 1 && sequence <= 4) {
                    counts[sequence]++;
                }
            }
        }

        return counts;
    }

    /**
     * Calculates the Unique Anchor value generated by the player's
     * Error Avatars.
     *
     * Sequence 1 = 10,000
     * Sequence 2 = 2,500
     * Sequence 3 = 500
     * Sequence 4 = 100
     */
    public static long getErrorAvatarUniqueAnchors(ServerPlayer player) {
        int[] counts = countErrorAvatarsBySequence(player);

        long total = 0L;

        total += (long) counts[1] * AnchorConfig.errorAvatarSequence1Anchors();
        total += (long) counts[2] * AnchorConfig.errorAvatarSequence2Anchors();
        total += (long) counts[3] * AnchorConfig.errorAvatarSequence3Anchors();
        total += (long) counts[4] * AnchorConfig.errorAvatarSequence4Anchors();

        return total;
    }

    /**
     * Temporary compatibility/debug method.
     */
    public static int countErrorAvatars(ServerPlayer player) {
        int[] counts = countErrorAvatarsBySequence(player);

        return counts[1]
                + counts[2]
                + counts[3]
                + counts[4];
    }
}